import Gabinete from "@/assets/NewProducts/Gabinete.webp";
import Monitor from "@/assets/NewProducts/Monitor.webp";
import Notebook from "@/assets/NewProducts/Notebook.webp";

export const NewData = [
  {
    id: crypto.randomUUID(),
    Stock: "in stock",
    img: Gabinete,
    Reviews: 5,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 1200,
  },
  {
    id: crypto.randomUUID(),
    Stock: "check availability",
    img: Monitor,
    Reviews: 4,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 800,
  },
  {
    id: crypto.randomUUID(),
    Stock: "in stock",
    img: Notebook,
    Reviews: 1,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 2500,
  },
  {
    id: crypto.randomUUID(),
    Stock: "in stock",
    img: Gabinete,
    Reviews: 5,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 1200,
  },
  {
    id: crypto.randomUUID(),
    Stock: "check availability",
    img: Monitor,
    Reviews: 4,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 800,
  },
  {
    id: crypto.randomUUID(),
    Stock: "in stock",
    img: Notebook,
    Reviews: 1,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 2500,
  },
  {
    id: crypto.randomUUID(),
    Stock: "in stock",
    img: Gabinete,
    Reviews: 5,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 1200,
  },
  {
    id: crypto.randomUUID(),
    Stock: "check availability",
    img: Monitor,
    Reviews: 4,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 800,
  },
  {
    id: crypto.randomUUID(),
    Stock: "in stock",
    img: Notebook,
    Reviews: 1,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 2500,
  },
  {
    id: crypto.randomUUID(),
    Stock: "in stock",
    img: Gabinete,
    Reviews: 5,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 1200,
  },
  {
    id: crypto.randomUUID(),
    Stock: "check availability",
    img: Monitor,
    Reviews: 4,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 800,
  },
  {
    id: crypto.randomUUID(),
    Stock: "in stock",
    img: Notebook,
    Reviews: 1,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 2500,
  },
];
