export const NewData = [
  {
    Stock: "in stock",
    img: "/gabinete.jpg",
    Reviews: 5,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 1200,
  },
  {
    Stock: "check availability",
    img: "/Monitor.jpg",
    Reviews: 4,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 800,
  },
  {
    Stock: "in stock",
    img: "/Notebook.jpg",
    Reviews: 1,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 2500,
  },
  {
    Stock: "in stock",
    img: "/gabinete.jpg",
    Reviews: 5,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 1200,
  },
  {
    Stock: "check availability",
    img: "/Monitor.jpg",
    Reviews: 4,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 800,
  },
  {
    Stock: "in stock",
    img: "/Notebook.jpg",
    Reviews: 1,
    Description: "ExDisplay: MSI pro 16 Flex-036AU 15.6 Multitouch All-In-One",
    OldPrice: 499,
    Price: 2500,
  },
];
